conda env export > environment_linux.yml
name: bert
channels:
  -pytorch
dependencies:
  - python=3.7
  - pytorch>=1.6
  - cudatoolkit
  - torchvision
  - torchaudio
  - h5py==2.10.0
  - bayesian-optimization
  - pip
  - pip:
      - simpletransformers