# conda env export --no-builds | grep -v "prefix" > environment_linux.yml

# conda env create --name datascience-deep-autoencoder --file=imported_packages.yml
name: vae
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - absl-py
  - boto3
  - numpy
  - pandas=1.1.3
  - scikit-learn
  - tqdm
  - pyyaml
  - scikit-image
  - pytest
  - pytest-cov
  - pyspark
  - tensorflow